// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cross/chain/height": {
            "get": {
                "description": "根据 chainId 获取扫描高度",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易记录"
                ],
                "summary": "获取扫描高度",
                "parameters": [
                    {
                        "type": "string",
                        "description": "chainId",
                        "name": "chainId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ChainHeightResponse"
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/cross/pending/tx": {
            "get": {
                "description": "根据 chainId 获取pending的交易列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易记录"
                ],
                "summary": "获取pending的交易列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "chainId",
                        "name": "chainId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PendingTxResponse"
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/cross/signle": {
            "get": {
                "description": "通过orderId获取交易记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易记录"
                ],
                "summary": "通过orderId获取交易记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "orderId",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CrossSignelResponse"
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        },
        "/cross/tx": {
            "get": {
                "description": "通过 txHash 获取交易记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易记录"
                ],
                "summary": "通过 txHash 获取交易记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "txHash",
                        "name": "tx",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CrossSignelResponse"
                        }
                    },
                    "400": {
                        "description": "bad request"
                    }
                }
            }
        }
    },
    "definitions": {
        "cross.CrossData": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string",
                    "example": ""
                },
                "chain_and_gas_limit": {
                    "type": "string",
                    "example": ""
                },
                "height": {
                    "type": "integer"
                },
                "is_memoized": {
                    "type": "boolean"
                },
                "log_index": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string",
                    "example": ""
                },
                "timestamp": {
                    "type": "integer"
                },
                "topic": {
                    "type": "string",
                    "example": ""
                },
                "tx_hash": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "cross.CrossSet": {
            "type": "object",
            "properties": {
                "dest": {
                    "$ref": "#/definitions/cross.CrossData"
                },
                "map_dest": {
                    "$ref": "#/definitions/cross.CrossData"
                },
                "now": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string",
                    "example": ""
                },
                "relay": {
                    "$ref": "#/definitions/cross.CrossData"
                },
                "src": {
                    "$ref": "#/definitions/cross.CrossData"
                },
                "status": {
                    "$ref": "#/definitions/cross.StatusOfCross"
                }
            }
        },
        "cross.StatusOfCross": {
            "type": "integer",
            "format": "int64",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "StatusOfInit",
                "StatusOfPending",
                "StatusOfSend",
                "StatusOfCompleted",
                "StatusOfFailed"
            ]
        },
        "main.ChainHeightResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "string"
                }
            }
        },
        "main.CrossSignelResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/cross.CrossSet"
                }
            }
        },
        "main.PendingTxResponse": {
            "type": "object",
            "properties": {
                "txs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6041",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "compass-tss-api",
	Description:      "tss跨链服务api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
